default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: euphoria_development
    username: postgres
    password: '123'
    host: localhost
    port: 5432

test:
  primary:
    <<: *default
    database: euphoria_test
    username: postgres
    password: '123'
    host: localhost
    port: 5432
  cable:
    <<: *default
    database: euphoria_test
    username: postgres
    password: '123'
    host: localhost
    port: 5432

production:
  primary:
    <<: *default
    database: euphoria_production
    username: euphoria
    password: '123'
    host: localhost
    port: 5432
  cable:
    <<: *default
    database: euphoria_production
    username: euphoria
    password: '123'
    host: localhost
    port: 5432