default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: euphoria_dev
    username: postgres
    password: 'postgres'
    host: localhost
    port: 5432

test:
  primary:
    <<: *default
    database: euphoria_test
    username: postgres
    password: 'postgres'
    host: localhost
    port: 5432
  cable:
    <<: *default
    database: euphoria_test
    username: postgres
    password: 'postgres'
    host: localhost
    port: 5432

production:
  primary:
    <<: *default
    database: euphoria_prod
    username: postgres
    password: 'postgres'
    host: localhost
    port: 5432
  cable:
    <<: *default
    database: euphoria_prod
    username: postgres
    password: 'postgres'
    host: localhost
    port: 5432